// Generated by CoffeeScript 1.9.2
(function() {
  var currPlayer, dictionary, doMove, drawTiles, endTurn, grid, newGame, player1, player2, selectTile, selectedCoordinates, showMessage, showThenFade, tileClick;

  grid = dictionary = currPlayer = player1 = player2 = selectedCoordinates = null;

  newGame = function() {
    var i, len, player, ref;
    grid = new Grid;
    dictionary = new Dictionary(OWL2, grid);
    currPlayer = player1 = new Player('Player 1', dictionary);
    player2 = new Player('Player 2', dictionary);
    drawTiles();
    player1.num = 1;
    player2.num = 2;
    ref = [player1, player2];
    for (i = 0, len = ref.length; i < len; i++) {
      player = ref[i];
      $("#p" + player.num + "name").html(player.name);
      $("#p" + player.num + "score").html(0);
    }
    return showMessage('firstTile');
  };

  drawTiles = function() {
    var gridHtml, i, j, ref, ref1, x, y;
    gridHtml = '';
    for (y = i = 0, ref = grid.tiles.length; 0 <= ref ? i < ref : i > ref; y = 0 <= ref ? ++i : --i) {
      gridHtml += '<ul>';
      for (x = j = 0, ref1 = grid.tiles.length; 0 <= ref1 ? j < ref1 : j > ref1; x = 0 <= ref1 ? ++j : --j) {
        gridHtml += "<li id='tile" + x + "_" + y + "'>" + grid.tiles[x][y] + "</li>";
      }
      gridHtml += '</ul>';
    }
    return $('#grid').html(gridHtml);
  };

  showMessage = function(messageType) {
    var messageHtml;
    switch (messageType) {
      case 'firstTile':
        messageHtml = "Please select your first tile.";
        break;
      case 'secondTile':
        messageHtml = "Please select a second tile.";
    }
    return $('#message').html(messageHtml);
  };

  tileClick = function() {
    var $tile, ref, x, y;
    $tile = $(this);
    if ($tile.hasClass('selected')) {
      selectedCoordinates = null;
      $tile.removeClass('selected');
      return showMessage('firstTile');
    } else {
      $tile.addClass('selected');
      ref = this.id.match(/(\d+)_(\d+)/).slice(1), x = ref[0], y = ref[1];
      return selectTile(x, y);
    }
  };

  selectTile = function(x, y) {
    if (selectedCoordinates === null) {
      selectedCoordinates = {
        x1: x,
        y1: y
      };
      return showMessage('secondTile');
    } else {
      selectedCoordinates.x2 = x;
      selectedCoordinates.y2 = y;
      $('#grid li').removeClass('selected');
      return doMove();
    }
  };

  doMove = function() {
    var $notice, moveScore, newWords, ref;
    ref = currPlayer.makeMove(selectedCoordinates), moveScore = ref.moveScore, newWords = ref.newWords;
    if (moveScore === 0) {
      $notice = $(currPlayer.name + " formed no words this turn.");
    } else {
      $notice = $("<p class=\"notice\">\n  " + currPlayer + " formed the following " + newWords.length + " word(s):<br />\n  <b>" + (newWords.join(', ')) + "</b><br />\n  earning <b>" + (moveScore / newWords.length) + "x" + newWords.length + " =\n  " + moveScore + "</b> points!\n</p>");
    }
    showThenFade($notice);
    return endTurn();
  };

  endTurn = function() {
    showMessage('firstTile');
    drawTiles();
    selectedCoordinates = null;
    $("#p" + currPlayer.num + "score").html(currPlayer.score);
    return currPlayer = currPlayer === player1 ? player2 : player1;
  };

  showThenFade = function($elem) {
    var animationTarget;
    $elem.insertAfter($('#grid'));
    animationTarget = {
      opacity: 0,
      height: 0,
      padding: 0
    };
    return $elem.delay(5000).animate(animationTarget, 500, function() {
      return $elem.remove();
    });
  };

  $(document).ready(function() {
    newGame();
    return $('#grid li').live('click', tileClick);
  });

}).call(this);

//# sourceMappingURL=jq5x5.js.map
